apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: managed-argocd-subscription
  namespace: managed-argocd
  labels:
    app: managed-argocd
  annotations:
    apps.open-cluster-management.io/github-path: clusters/live/lab/argocd-cluster-policies
    apps.open-cluster-management.io/github-branch: lab
spec:
  channel: managed-argocd/managed-argocd
  placement:
    local: true