apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor
  namespace: stackrox
  spec:
    replicas: 1
status:
  conditions:
    - status: "True"
      type: Available
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: collector
  namespace: stackrox
status:
  numberMisscheduled: 0
