apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: stackrox-central-services
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  configAsCode:
    configAsCodeComponent: Enabled
  monitoring:
    openshift:
      enabled: true
  network:
    policies: Enabled
  central:
    #nodeSelector:
    #  node-role.kubernetes.io/infra: ""
    #tolerations:
    #  - key: node-role.kubernetes.io/infra
    #    effect: NoSchedule
    notifierSecretsEncryption:
      enabled: false
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true
    telemetry:
      enabled: true
    db:
      resources:
        limits:
          cpu: "1"
          memory: "4Gi"
        requests:
          cpu: "500m"
          memory: "2Gi"
      #nodeSelector:
      #  node-role.kubernetes.io/infra: ""
      #tolerations:
      #  - key: node-role.kubernetes.io/infra
      #    effect: NoSchedule
      isEnabled: Default
      persistence:
        persistentVolumeClaim:
          claimName: central-db
    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
  egress:
    connectivityPolicy: Online
  scannerV4:
    db:
      #nodeSelector:
      #  node-role.kubernetes.io/infra: ""
      #tolerations:
      #  - key: node-role.kubernetes.io/infra
      #    effect: NoSchedule
      persistence:
        persistentVolumeClaim:
          claimName: scanner-v4-db
  scanner:
    analyzer:
      #nodeSelector:
      #  node-role.kubernetes.io/infra: ""
      #tolerations:
      #  - key: node-role.kubernetes.io/infra
      #    effect: NoSchedule
      scaling:
        autoScaling: Disabled
        #maxReplicas: 3
        #minReplicas: 1
        replicas: 1
